<?php
/**
 * The template for displaying posts in the Venue post format
 *
 * @package WordPress
 * @subpackage U-design
 * @since Ven
 */
?>
<?php
	$screen_date = isset($_GET['s_date']) ? trim($_GET['s_date']) : '';

?>

<article <?php post_class(); ?> id="post-<?php the_ID(); ?>">
	<header class="entry-header">

		<?php
			global $post;
			/* the_title( '<h1 class="entry-title">', '</h1>' );
			echo $post->ID; */
			echo '<h1 class="entry-title">'.get_the_title($post->ID).'</h1>';
		?>
	</header><!-- .entry-header -->
<?php       udesign_single_post_entry_before(); ?>
                 <div class="entry" style="font-size:10px;">
<?php                  udesign_single_post_entry_top();

                       if( $udesign_options['display_post_image_in_single_post'] == 'yes' ) display_post_image_fn( $post->ID, false );

                       $event = em_get_event($post->ID);

                       //PRINT SHOW_TIMES
                       //get all showdates

                       //print content
                       $movie_info_array = get_field("movie");
						//my_var_dump($movie_info_array);
						$movie = $movie_info_array;
					   if(is_array($movie_info_array))
					   		$movie = $movie_info_array[0];

					   //print movie info
					   if($movie)
					   		$image = get_movie_image($movie);
?>
	<!-- 	<div class="movie_thumb"> -->
		 <img src="<?php echo DENVER_ROOT.$image;?>" width="292" height="158"/>
		<!-- </div> -->
		<div class="clear"></div>
<?php
			//prints single event info generated by events setting...
			// the_content(__('<p class="serif">Read the rest of this entry &raquo;</p>', 'udesign'));

			//get movie info....
			$movie_content = apply_filters('the_content_movie_thumbnail', $movie);
			echo $movie_content;
?>
			    </div>
<?php                       udesign_single_post_entry_after(); ?>
</article>