<?php
/**
 * The template for displaying posts in the Venue post format
 *
 * @package WordPress
 * @subpackage U-design
 * @since Ven
 */
?>

<article <?php post_class(); ?> id="post-<?php the_ID(); ?>">
		<header class="entry-header">

		<?php
			global $post;
			if ( is_single() ) :
				the_title( '<h1 class="entry-title">', '</h1>' );
			else :
				the_title( '<h1 class="entry-title"><a href="' . esc_url( get_permalink() ) . '" rel="bookmark">', '</a></h1>' );
			endif;
		?>
	</header><!-- .entry-header -->
<?php       udesign_single_post_entry_before(); ?>
                 <div class="entry">
<?php                  udesign_single_post_entry_top();
                       if( $udesign_options['display_post_image_in_single_post'] == 'yes' ) display_post_image_fn( $post->ID, false );

                       //print content
                		$movie = $post;

					   //print movie info

					   if(!empty($movie)):
					   		$image = get_movie_image($movie);
?>
	<figure>
		<img src="<?php echo DENVER_ROOT.$image;?>" />
		<figcaption><?php the_title();?></figcaption>
	</figure>
<?php
					endif;
			//prints single event info generated by events setting...
			//get movie info....

			$movie_content = apply_filters('the_content_movie', $movie);
			echo $movie_content;
?>
<?php
						wp_link_pages(array('before' => '<p><strong>Pages:</strong> ', 'after' => '</p>', 'next_or_number' => 'number')); ?>

<?php                       //    udesign_single_post_entry_bottom(); ?>
			    </div>
<?php                       udesign_single_post_entry_after(); ?>
</article><!-- #post-## -->